# Generated by Django 5.1 on 2024-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
