# Generated by Django 5.1.2 on 2024-11-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0007_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
