# Generated by Django 5.1 on 2024-12-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_duowrapped_llm_comparison_duowrapped_llm_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duowrappedinvite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='duowrappedinvite',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='duowrappedinvite',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friendconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendconnection',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendconnection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DuoWrapped',
        ),
        migrations.DeleteModel(
            name='DuoWrappedInvite',
        ),
        migrations.DeleteModel(
            name='FriendConnection',
        ),
        migrations.DeleteModel(
            name='SpotifyProfile',
        ),
    ]
