# Generated by Django 5.1 on 2024-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_duowrappedinvite_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyWrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
